### ISSUE TITLE
안드로이드 초기 세팅

### ISSUE THREAD

**Issue by ricky-o-k** [Nexters/winepick-android#1]
```
아래 내용은 변동될 수 있음
```

## TodoList
1. Base 구축 및 적용시켜보고 싶은 기능 이야기해보기
2. 협업 방법 정하기

## BackLog
1. 기능 정의 내용을 토대로 개발하는 방법 정해보기
   1. 화면별로 진행
   2. 기능별로 진행(?)

**Comment by ricky-o-k** [comment]
개인적으로 생각한 내용
1. MVVM 기반으로 아키텍쳐를 구성하며 데이터바인딩 필수로 적용 
   (사유 : `kotlin android extension` 이 `Deprecated` 되었고 `findViewById` 도 논란이 많음)
2. `ViewModel` 은 사용하고 싶은 경우에 사용할 수 있도록 처리
3. 네트워크 : `Retrofit2`
4. 테스트 : Robolectric + MockK, ( + Hilt)
5. CI / CD : GitHub actions
    현재 tag 를 push 할 때 마다 apk 를 업로드하는 걸 고려해보고 있으나,  GitHub actions 로그 자체에 유통기한이 있어 고민
    슬랙도 생각중이나 넥스터즈 슬랙은 어려울 것 같고, 팀 전용 슬랙으로 해야할 것 같은데, 슬랙 채널이 하나 더 생기는 것이기 때문에 우려
6. Rx? Coroutine?

**Comment by yunakim2** [comment]
GitHub Action을 안써봤긴한데 써보면 좋을거같아요 ! 나머지의견은 상우님의견을 따르겠슴다...👀

**Comment by ricky-o-k** [comment]
아아 그냥 이번 플젝에서 적용해볼까 싶은...? 거 생각만 정리했던거여섴ㅋㅋㅋㅋㅋㅋ 
나머지 분들도 적용해보고 싶은거나 해보고 싶은 거 자유롭게 이야기해주세요 ㅋㅋㅋㅋ

**Comment by yunakim2** [comment]
1. `MVVM`
2. 네트워크 : `Retrofit2`
3. `Hilt` 랑 `Koin`의 차이를 명확히는 모르겠는데 `Koin`은 사용해봐서 `Hilt`도 사용해보면 좋을거같슴다
4. Rx 관련 책으로 공부하고 있기는 한데 Coroutine도 안해봐서 공부하면서 적용해보면 좋겠네요

**Comment by anyl92** [comment]
저는 앱 쪽 생태계도 잘 모르고 신기술 이런 것도 잘 몰라서 정말 정해주시는대로 알아가며 진행해야될거같아요!
apk도 마찬가지로 원래 어떤 방식으로 진행되는지 몰라서, 슬랙이 베스트라면 우선 슬랙 임시로 쓰고 종료되거나 다른거 쓰게 되면 삭제하거나 ㅎㅎ 그렇게 정리하면 어때요?

개발방법은 페이지별로 하면 어떨까 싶네요. 기능별로 한다면 같은 페이지 내에서 함께 코드작성할 수도 있을거같은데 조금 애매하지 않을까 싶어요! 근데 그냥 생각해본거고 어떤 방식이든 관계없습니다~~
