### ISSUE TITLE
[bug] 검색 및 로그인 화면 피드백

### ISSUE THREAD

**Issue by ricky-o-k** [Nexters/winepick-android#26]
[pdf 내용](https://github.com/Nexters/winepick-android/files/5977859/_.0214.pdf) 참고하여 진행

**Comment by riflockle7** [comment]
[상우님_와인픽0214피드백.pdf](https://github.com/Nexters/winepick-android/files/5977859/_.0214.pdf)

**Comment by yunakim2** [comment]
확인했습니다..!
